/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiButton {
        "appearance": string;
        "label": string;
        "type": string;
    }
    interface UiCard {
        "imageBack"?: string;
        "imageFront"?: string;
    }
    interface UiInput {
        "active": string;
        "type": string;
        "value": string;
    }
}
declare global {
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiCardElement extends Components.UiCard, HTMLStencilElement {
    }
    var HTMLUiCardElement: {
        prototype: HTMLUiCardElement;
        new (): HTMLUiCardElement;
    };
    interface HTMLUiInputElement extends Components.UiInput, HTMLStencilElement {
    }
    var HTMLUiInputElement: {
        prototype: HTMLUiInputElement;
        new (): HTMLUiInputElement;
    };
    interface HTMLElementTagNameMap {
        "ui-button": HTMLUiButtonElement;
        "ui-card": HTMLUiCardElement;
        "ui-input": HTMLUiInputElement;
    }
}
declare namespace LocalJSX {
    interface UiButton {
        "appearance"?: string;
        "label"?: string;
        "type"?: string;
    }
    interface UiCard {
        "imageBack"?: string;
        "imageFront"?: string;
    }
    interface UiInput {
        "active"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "ui-button": UiButton;
        "ui-card": UiCard;
        "ui-input": UiInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-card": LocalJSX.UiCard & JSXBase.HTMLAttributes<HTMLUiCardElement>;
            "ui-input": LocalJSX.UiInput & JSXBase.HTMLAttributes<HTMLUiInputElement>;
        }
    }
}
